# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a671b1f6cd012e365c4025f09d05dce546360a5d2eb65880e74f63fb2f79d889e65125457cdbb7954f388d155da4726c5f1c753d4377a1fd937bb0a966cf037

test:
  secret_key_base: d1d322669f2a9cc13f3c350a24f84ba68dbdfc3ae7c64a587cb959a0ebbed6db0f54bb0626d6247ce04406ea9bea3223fd777603134e9d0dc7572e26197bc81b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
